{"uuid": "a8de7d2f-e4f8-4053-818a-bbc22ae2c40b", "children": ["d18317ee-7588-4bc2-a908-d2b1c8d056fc", "70d3bc93-1592-4ec0-8c69-bebf1ae10050", "ac650c26-7119-42c7-8bb9-83494449e477", "c8c82d3a-92f4-418a-a0a9-99d643674bb1", "61c11d1d-1553-40ba-bc8f-af15004284cc", "a2ccdbb9-ebdf-4d01-8840-0b08ad5f9ecb", "ea6ab7c5-4377-4af5-bd4e-55412cf1943e", "7423e181-bd73-4670-9e94-d90a4d517d72", "0b5bb9fc-adb9-4b2e-aa53-5b20d9e8f51a", "b843064b-2ce9-4af3-abd8-042eea897d74", "5d01ef69-2338-4714-a5dc-b6b7d4510226", "0ad758b5-e5f2-425a-a341-cf17fbbaf4ad", "dcb28d37-37b5-40b6-985a-038954b9b238"], "befores": [{"name": "setup", "status": "passed", "start": 1678426340037, "stop": 1678426349224}], "afters": [{"name": "setup::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: disconnected: not connected to DevTools\n  (failed to check if window was closed: disconnected: not connected to DevTools)\n  (Session info: chrome=110.0.5481.178)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x010B37D3]\n\t(No symbol) [0x01048B81]\n\t(No symbol) [0x00F4B36D]\n\t(No symbol) [0x00F3BE5A]\n\t(No symbol) [0x00F3C63A]\n\t(No symbol) [0x00F3C5D8]\n\t(No symbol) [0x00F2D0BA]\n\t(No symbol) [0x00F2DBA7]\n\t(No symbol) [0x00FA489B]\n\t(No symbol) [0x00F9B3E3]\n\t(No symbol) [0x00F70D97]\n\t(No symbol) [0x00F7253D]\n\tGetHandleVerifier [0x0132ABF2+2510930]\n\tGetHandleVerifier [0x01358EC1+2700065]\n\tGetHandleVerifier [0x0135C86C+2714828]\n\tGetHandleVerifier [0x01163480+645344]\n\t(No symbol) [0x01050FD2]\n\t(No symbol) [0x01056C68]\n\t(No symbol) [0x01056D4B]\n\t(No symbol) [0x01060D6B]\n\tBaseThreadInitThunk [0x75B300F9+25]\n\tRtlGetAppContainerNamedObjectPath [0x76FA7BBE+286]\n\tRtlGetAppContainerNamedObjectPath [0x76FA7B8E+238]\n\n", "trace": "  File \"C:\\Users\\graveendran\\PycharmProjects\\pyTestProject\\venv\\Lib\\site-packages\\allure_commons\\_allure.py\", line 221, in __call__\n    return self._fixture_function(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\graveendran\\PycharmProjects\\pyTestProject\\venv\\Lib\\site-packages\\_pytest\\fixtures.py\", line 917, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\graveendran\\PycharmProjects\\pyTestProject\\tests\\conftest.py\", line 34, in setup\n    driver.close()\n  File \"C:\\Users\\graveendran\\PycharmProjects\\pyTestProject\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 551, in close\n    self.execute(Command.CLOSE)\n  File \"C:\\Users\\graveendran\\PycharmProjects\\pyTestProject\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\graveendran\\PycharmProjects\\pyTestProject\\venv\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1678426376635, "stop": 1678426376639}], "start": 1678426340037, "stop": 1678426376639}